### ISSUE TITLE
Assembler uses `x6` (`t1`) as "assembler reserved register" to translate "call" and "tail" pseudo-instructions

### ISSUE THREAD

**Issue by pacalet** [rarsm/rars#105]
The assembler translates `call label` as a `auipc` / `jalr` pair:

```
auipc x6,imm1
jalr  x1,x6,imm2
```

It uses register `x6` (`t1`) to do so while register `x1` (`ra`) is available and must indeed be modified anyway to store the return address. Although the ILP32 Application Binary Interface (ABI) and other ABIs consider `x6` as non-saved, I do not see any reason to enforce an ABI in RARS more than strictly needed. So, I suggest to translate `call label` as:

```
auipc x1,imm1
jalr  x1,x1,imm2
```

Pull request submitted.

Note: one could claim that this is still ABI-related because we use `x1` (`ra`). But using a register is unavoidable if one wants a `call` pseudo-instruction. Choosing `x1` makes sense as it is the preferred register for this purpose in ILP32 and alike.

Note: another pseudo-instruction (and only one) also silently modifies a non-saved register: `tail label`. As its target register is `x0` we cannot fix it as we did for `call`. My intuition is that `tail` shall be removed completely but this breaks backward compatibility. We should maybe add a warning in its brief description?

**Comment by privat** [comment]
fixed by #104
